# Generated by Django 2.1.3 on 2019-10-31 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumtag',
            old_name='album',
            new_name='al',
        ),
        migrations.RenameField(
            model_name='artisttag',
            old_name='artist',
            new_name='art',
        ),
    ]
